# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf746a742090f88c4116733b83bd7533dc905d37b5ea9d17333c01b5b96d835bbc71c619ae5ff4162076d72441aa22e31cb57504e18b31142285c09a82b3c271

test:
  secret_key_base: 49b8406f321cca85a5f6db8a169c1c966d4c10e0bcdb15cf94b7f847acee0251f0036a0304522848895896451e81a5db795a8b3de0552270b75e9b111b554685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
